package SmartHome;


/**
* SmartHome/_HouseImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from House.idl
* 03 April 2017 16:58:08 o'clock IST
*/

public abstract class _HouseImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements SmartHome.House, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _HouseImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("turnOnLights", new java.lang.Integer (0));
    _methods.put ("turnOffLights", new java.lang.Integer (1));
    _methods.put ("turnOnHeating", new java.lang.Integer (2));
    _methods.put ("turnOffHeating", new java.lang.Integer (3));
    _methods.put ("lockDoors", new java.lang.Integer (4));
    _methods.put ("unlockDoors", new java.lang.Integer (5));
    _methods.put ("armAlarm", new java.lang.Integer (6));
    _methods.put ("disarmAlarm", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // SmartHome/House/turnOnLights
       {
         String $result = null;
         $result = this.turnOnLights ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // SmartHome/House/turnOffLights
       {
         String $result = null;
         $result = this.turnOffLights ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // SmartHome/House/turnOnHeating
       {
         String $result = null;
         $result = this.turnOnHeating ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // SmartHome/House/turnOffHeating
       {
         String $result = null;
         $result = this.turnOffHeating ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // SmartHome/House/lockDoors
       {
         String $result = null;
         $result = this.lockDoors ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // SmartHome/House/unlockDoors
       {
         String $result = null;
         $result = this.unlockDoors ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // SmartHome/House/armAlarm
       {
         String $result = null;
         $result = this.armAlarm ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // SmartHome/House/disarmAlarm
       {
         String $result = null;
         $result = this.disarmAlarm ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SmartHome/House:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _HouseImplBase
