package SmartHome;


/**
* SmartHome/HouseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from House.idl
* 04 April 2017 20:10:04 o'clock IST
*/

public interface HouseOperations 
{
  String lightsOn (String status);
  String lightsOff (String status);
} // interface HouseOperations
