package SmartHome;


/**
* SmartHome/HouseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from House.idl
* 03 April 2017 19:08:03 o'clock IST
*/

public interface HouseOperations 
{
  String lights ();
} // interface HouseOperations
