package SmartHome;


/**
* SmartHome/HouseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from House.idl
* 08 April 2017 12:42:27 o'clock IST
*/

public interface HouseOperations 
{
  String lights (String status);
  String alarm (String status);
  String door (String status);
  String heating (String status);
} // interface HouseOperations
