package SmartHome;


/**
* SmartHome/House.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from House.idl
* 25 March 2017 14:31:49 o'clock GMT
*/

public interface House extends HouseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface House
