package SmartHome;


/**
* SmartHome/HouseHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from House.idl
* 04 April 2017 19:31:11 o'clock IST
*/

abstract public class HouseHelper
{
  private static String  _id = "IDL:SmartHome/House:1.0";

  public static void insert (org.omg.CORBA.Any a, SmartHome.House that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SmartHome.House extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (SmartHome.HouseHelper.id (), "House");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SmartHome.House read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_HouseStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SmartHome.House value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static SmartHome.House narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SmartHome.House)
      return (SmartHome.House)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SmartHome._HouseStub stub = new SmartHome._HouseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static SmartHome.House unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SmartHome.House)
      return (SmartHome.House)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SmartHome._HouseStub stub = new SmartHome._HouseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
