package SmartHome;


/**
* SmartHome/House.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from House.idl
* 03 April 2017 16:58:08 o'clock IST
*/

public interface House extends HouseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface House
